# description
name: "HashTabber"
description: "Short description"
author: "Leszek Pietrzak"

# address settings
url: "http://hashtabber.smutnyleszek.com"
permalink: /post/:title

# site configuration
encoding: UTF-8
markdown: rdiscount
future: true
paginate: 9000