# description
name: "hashTabber"
description: "Short description"
author: "Leszek Pietrzak"

# address settings
#url: "http://hashtabber.smutnyleszek.com"
url: "http://0.0.0.0:4000"
permalink: /post/:title

# site configuration
encoding: UTF-8
markdown: rdiscount
future: true
paginate: 9000